# Name of the workflow
name: Build and publish image to DockerHub

# This is where we define what triggers this workflow. So here, when we push to master AND those either of those Dockerfiles has been modified, then this workflow will trigger and upload our images to DockerHub.
on:
  push:
    branches:
      - master
    paths:
      - "api/Dockerfile"
      - "front-end-nextjs/Dockerfile"

# This is where we define the job. In this case, we build both images and push them to DockerHub. We made an access token for github and added it to our secrets in GitHub Actions, allowing us to access it here with secrets.DOCKER_HUB_TOKEN.
jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          docker build ./api/ -t markfinerty/devops-qr-code-backend:latest
          docker build ./front-end-nextjs/ -t markfinerty/devops-qr-code-frontend:latest
      - name: push image to docker hub
        run: |
          docker login -u markfinerty -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push markfinerty/devops-qr-code-backend:latest
          docker push markfinerty/devops-qr-code-frontend:latest
